import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "SkinSight",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <div className="el" />
          <header style={{display:'flex', alignItems: 'center', backgroundColor: '#374151', padding: '16px', height: '8vh'}}>
          <Link href="/" style={{color:"ivory", fontSize:"24px", fontWeight:'bold', marginRight:'24px'}}>SkinSight</Link>
          <Link href="/upload" style={{color:"ivory", fontSize:"20px", fontWeight: 'normal', marginRight:'24px'}}>
            Get Started
          </Link>
        </header>
             <div style={{display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
                 {children}
              </div>
      </body>
    </html>
  );
}
